---
title: "Homework Assignment 4"
author: "Vincent Xie"
toc: true
number-sections: true
highlight-style: pygments
format: 
  pdf: 
    geometry: 
      - top=30mm
      - left=20mm
---

# **NYC rodent sightings data cleaning** {.unnumbered}

The data appears to need some cleaning before any further analysis.
Some missing values could be filled based on other columns.

**Data Initialization**

```{python}
import numpy as np
import pandas as pd
import os
pd.options.mode.chained_assignment = None

data = pd.read_csv("data/rodent_2022-2023.csv")
```

   1. Checking all 47 column names suggests that some columns 
   might be redundant. Identify them and demonstrate the redundancy.

```{python}
print(data.columns)
```

**Answer:** 

Agency vs. Agency Name:

- One is an abbrevation of the full name.
- One can be removed to reduce repetitiveness.

Incident Address vs. Street Name vs. Landmark:

- Landmark and Street Name are identical.
- Both of these values are contained in Incident Address so we only need one of the columns.

Cross Street 1/2 vs. Intersection Street 1/2:

- Repetitiveness within these columns.
- Only one needs to be removed.

Park Facility Name:

- Unspecified so the inputs do not have much value.

Park Borough:

- Identical to Community Board and Borough.
- Column is adding to the repetitiveness.

Police Precincts vs. Police Precinct:

- Identical values so one can be removed.

Location:

- Longitude and latitude are contained in the Location column so it can be removed as it is redundant.

Empty Columns:

- Facility Type
- Due Date
- Vehicle Type
- Taxi Company Borough
- Taxi Pick Up Location
- Bridge Highway Name
- Bridge Highway Direction
- Road Ramp
- Bridge Highway Segment

Columns we can remove to clean data:

- Agency Name
- Street Name
- Landmark
- Intersection Street 1
- Intersection Street 2
- Park Facility Name
- Park Borough
- Police Precinct
- Longitude
- Latitude
- Facility Type
- Due Date
- Vehicle Type
- Taxi Company Borough
- Taxi Pick Up Location
- Bridge Highway Name
- Bridge Highway Direction
- Road Ramp
- Bridge Highway Segment


   2. Are zip code and borough always missing together? If geocodes
   are available, use reverse geocoding to fill the zip code.

```{python}
missing_zip = data['Zip Codes'].isnull()
missing_borough = data['Borough'].isnull()
missing_zip_borough_correlation = (missing_zip == missing_borough).all()
geocode_available = not (data['Latitude'].isnull().any() 
                    or data['Longitude'].isnull().any())

missing_zip_borough_correlation, geocode_available
```

**Answer:** From the results, we see that zip codes and boroughs are not always missing together. Geocoding is also not available because there are some null values with no location.

   3. Export the cleaned data in both csv and feather format. 
   Comment on the file sizes.

```{python}
columns_to_remove = ['Agency Name', 'Street Name', 'Landmark',
                     'Intersection Street 1', 'Intersection Street 2',
                     'Park Facility Name', 'Park Borough', 'Police Precinct',
                     'Longitude', 'Latitude', 'Facility Type', 'Due Date',
                     'Vehicle Type', 'Taxi Company Borough', 'Taxi Pick Up Location',
                     'Bridge Highway Name', 'Bridge Highway Direction', 'Road Ramp',
                     'Bridge Highway Segment']
cleaned_data = data.drop(columns=columns_to_remove)

# Exporting
csv_file_path = 'data/cleaned_rodent_data.csv'
feather_file_path = 'data/cleaned_rodent_data.feather'

# CSV Export
cleaned_data.to_csv(csv_file_path, index=False)

# Feather Export (removing non-supported types like datetime)
cleaned_data['Created Date'] = cleaned_data['Created Date'].astype(str)
cleaned_data['Closed Date'] = cleaned_data['Closed Date'].astype(str)
cleaned_data.to_feather(feather_file_path)

# Checking the file sizes
csv_file_size = os.path.getsize(csv_file_path)
feather_file_size = os.path.getsize(feather_file_path)

csv_file_size, feather_file_size
```

**Answer**: The size of the csv files come out to 42 million bytes. The size of the feather file comes out to roughly 16 million bytes. We see that feather formatting is significantly smaller.